#!/bin/bash

	#################################################
	#    Programa que valida informações com grep   #
	#             Data: 25/02/2018	        	#
	#		Alexandre			#		
	#################################################
	
	
NOME(){
	read -p "Digite o seu nome: " nome	
	echo $nome | grep -E '^[0-9.-\=_,><?:;!@#$%¨&*()_+\""][ ]$'
	if [ $? == 1 ]; then
		clear
		echo "Nome válido!"
		sleep 1
		clear
		EMAIl
	else
		echo "Nome inválido!"
		echo "Digite novamente:"
		sleep 1
		clear
		NOME
	fi
}

EMAIL(){
	read -p "Digite o seu email: " email	
	echo $email | grep -E '^(A-Za-z0-9\.\_\-)+[@][A-Za-z0-9]+(\.com|\.br)|(\.com\.br)$'
	if [ $? == 1 ]; then
		clear
		echo "Email válido!"
		sleep 1
		clear
		TELEFONE
	else
		echo "Email inválido!"
		echo "Digite novamente:"
		sleep 1
		clear
		EMAIL
	fi
}

TELEFONE(){
	echo "Formato do telefone: (XX)XXXX-XXXX"
	read -p "Digite o seu telefone: " telefone	
	echo $telefone | grep -E '^[(][0-9]{2}[)][0-9]{4}+-[0-9]{4}$'
	if [ $? == 0 ]; then
		clear
		echo "Telefone válido!"
		sleep 3
		clear
		RG
	else
		echo "Telefone inválido!"
		echo "Digite novamente:"
		sleep 3
		clear
		TELEFONE
	fi
}


RG(){
	echo "Formato do documento: XX.XXX.XXX-X"
	read -p "Digite o seu rg: " rg	
	echo $rg | grep -E '^[(][0-9]{2}[)][0-9]{4}+-[0-9]{4}$'
	if [ $? == 0 ]; then
		clear
		echo "RG válido!"
		sleep 3
		clear
		CPF
	else
		echo "RG inválido!"
		echo "Digite novamente:"
		sleep 3
		clear
		RG
	fi
}

CPF(){
	echo "Formato do documento: XXX.XXX.XXX-XX"
	read -p "Digite o seu cpf " cpf	
	echo $cpf | grep -E '^[0-9]{3}[.][0-9]{3}[.][0-9]{3}[-][0-9]{2}$'
	if [ $? == 0 ]; then
		clear
		echo "CPF válido!"
		sleep 2
		clear
		NASC
	else
		echo "CPF inválido!"
		echo "Digite novamente:"
		sleep 2
		clear
		CPF
	fi
}

NASC(){
	echo "Formato da data: XX/XX/XXXX"
	read -p "Digite a data de seu nascimento " nasc	
	echo $nasc | grep -E '^[0-9]{2}\/[0-9]{2}\/[0-9]{4}$'
	if [ $? == 0 ]; then
		clear
		echo "A data está correta!"
		sleep 2
		clear
		NASC
	else
		echo "A data está incorreta!"
		echo "Digite novamente:"
		sleep 2
		clear
		CPF
	fi
}

IP(){
        read -p "Digite o seu ip: " ip
        		
		echo $ip | grep -E '^([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])){3}$'
		
		if [ $? == 0 ]; then
		clear
		echo "O ip é valido!"
		sleep 2
		clear
		MASK
	else
		echo "O ip é invalido!"
		echo "Digite novamente:"
		sleep 2
		clear
		IP
	fi
    }

MASK(){
        read -p "Digite a sua máscara de rede: " mask
        		
		echo $mask | grep -E '^([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])){3}$'
		
		if [ $? == 0 ]; then
		clear
		echo "A máscara é valida!"
		echo " Cadastro efetuado com sucesso"
		sleep 2
		clear
		
	else
		echo "A máscara é inválida!"
		echo "Digite novamente:"
		sleep 2
		clear
		MASK
	fi
  
}
NOME



























